// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEicUOVwhI5e3gHKWm3LSV2AmRZHq_DgU',
    appId: '1:347881301093:web:afc9e222af6930e5a4d28c',
    messagingSenderId: '347881301093',
    projectId: 'testagain-a95cb',
    authDomain: 'testagain-a95cb.firebaseapp.com',
    storageBucket: 'testagain-a95cb.firebasestorage.app',
    measurementId: 'G-1BC3D5V7SC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa-UElFFDN4U-ABJP5XaGhqWXmGW7854w',
    appId: '1:347881301093:android:deffaaef35fdb83aa4d28c',
    messagingSenderId: '347881301093',
    projectId: 'testagain-a95cb',
    storageBucket: 'testagain-a95cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA73M6_98EjzzYsCpxvI-x0FZ8M2h-h1gk',
    appId: '1:347881301093:ios:bb355ec601a37f0da4d28c',
    messagingSenderId: '347881301093',
    projectId: 'testagain-a95cb',
    storageBucket: 'testagain-a95cb.firebasestorage.app',
    iosBundleId: 'com.example.newnew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA73M6_98EjzzYsCpxvI-x0FZ8M2h-h1gk',
    appId: '1:347881301093:ios:bb355ec601a37f0da4d28c',
    messagingSenderId: '347881301093',
    projectId: 'testagain-a95cb',
    storageBucket: 'testagain-a95cb.firebasestorage.app',
    iosBundleId: 'com.example.newnew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEicUOVwhI5e3gHKWm3LSV2AmRZHq_DgU',
    appId: '1:347881301093:web:5ccf859c89185d1ca4d28c',
    messagingSenderId: '347881301093',
    projectId: 'testagain-a95cb',
    authDomain: 'testagain-a95cb.firebaseapp.com',
    storageBucket: 'testagain-a95cb.firebasestorage.app',
    measurementId: 'G-PHPZXW8YSN',
  );
}
